image: python:3.12

stages:
  - linting
  - test
  - deploy

before_script:
  - ln -sf /usr/bin/python3 /usr/bin/python  # Ensure 'python' is available
  - python3 -m ensurepip --default-pip  # Ensure pip is installed
  - python3 -m pip install --upgrade pip
  - pip install poetry
  # if job is triggered by a schedule, run poetry update to update dependencies
  - if [ "$CI_PIPELINE_SOURCE" == "schedule" ]; then poetry update; fi
  - poetry config virtualenvs.in-project true
  - poetry install --with tests
  - source .venv/bin/activate

.run_test_with_coverage: &run_test_with_coverage
  - coverage run tests/test_basic.py
  - coverage report -m || true

## linting
pre_commit:
  stage: linting
  before_script:
    - pip install pre-commit
  script:
    - pre-commit run --all-files --show-diff-on-failure

## test
test_python_versions:
  stage: test
  image: python:3.12
  parallel:
    matrix:
      - PYTHON_VERSIONS: [ "3.9", "3.10", "3.11", "3.12" ]
  script:
    - *run_test_with_coverage

test_latest_python_version_with_coverage:
  stage: test
  image: python:3.12
  script:
    - *run_test_with_coverage
    - coverage xml
  coverage: '/(?i)total.*? (100(?:\.0+)?\%|[1-9]?\d(?:\.\d+)?\%)$/'
  artifacts:
    reports:
      coverage_report:
        coverage_format: cobertura
        path: coverage.xml

## deploy
pages:
  # push the latest documentation of the main branch to the Gitlab pages.
  # available at https://cps.pages.gitlab.lrz.de/commonroad/commonroad-template
  stage: deploy
  publish: site
  script:
    - poetry install --with docs
    - mkdocs build
  artifacts:
    paths:
      - site
  environment:
    name: Gitlab Pages
    url: https://cps.pages.gitlab.lrz.de/commonroad/commonroad-template

build_and_push_to_pypi_test:
  stage: deploy
  when: manual
  script:
    - poetry config repositories.test https://test.pypi.org/legacy/  # skip for official pypi
    - poetry build
    - poetry publish --repository test -u __token__ -p ${CR_PYPI_TEST_API_TOKEN}  # use ${CR_PYPI_RELEASE_API_TOKEN} for official pypi
