image: python:3.10

stages:
  - linting
  - test
  - deploy

before_script:
  - apt-get update
  - apt-get install -y libgl1
  - pip install poetry
  - poetry config virtualenvs.in-project true
  - poetry config http-basic.cr_reach_flow-gitlab gitlab-ci-token $CI_JOB_TOKEN
  - poetry config http-basic.commonroad_cpp-gitlab gitlab-ci-token $CI_JOB_TOKEN
  - git config --global url."https://gitlab-ci-token:${CI_JOB_TOKEN}@gitlab.lrz.de".insteadOf "ssh://git@gitlab.lrz.de"
  - git config --global url."https://gitlab-ci-token:${CI_JOB_TOKEN}@gitlab.lrz.de/".insteadOf "git@gitlab.lrz.de:"
  # if job is triggered by a schedule, run poetry update to update dependencies
  - if [ "$CI_PIPELINE_SOURCE" == "schedule" ]; then poetry update; fi
  - poetry install -vvv --extras tests
  - source .venv/bin/activate

.run_test_with_coverage: &run_test_with_coverage
  - coverage run tests/test_basic.py
  - coverage report -m || true

## linting
pre_commit:
  stage: linting
  before_script:
    - pip install pre-commit
  script:
    - pre-commit run --all-files --show-diff-on-failure

## test
test_python_versions:
  stage: test
  image: python:$PYTHON_VERSIONS
  parallel:
    matrix:
      - PYTHON_VERSIONS: [ "3.10" ]
  script:
    - *run_test_with_coverage


# deploy
pages:
  # push the latest documentation of the main branch to the Gitlab pages.
  # available at https://cps.pages.gitlab.lrz.de/commonroad/commonroad-template
  stage: deploy
  # when: manual
  only:
    - dev
  publish: site
  script:
    - poetry install --with docs
    - mkdocs build
  artifacts:
    paths:
      - site
  environment:
    name: Gitlab Pages
    url: https://cps.pages.gitlab.lrz.de/commonroad/commonroad-template

build_and_push_to_pypi_test:
  stage: deploy
  when: manual
  only:
    - main
  script:
    - poetry config repositories.test https://test.pypi.org/legacy/  # skip for official pypi
    - poetry build
    - poetry publish --repository test -u __token__ -p ${CR_PYPI_TEST_API_TOKEN}  # use ${CR_PYPI_RELEASE_API_TOKEN} for official pypi
