site_name: Criticality-Enhancement
theme:
  name: material
  logo: assets/commonroad_white150.png
plugins:
  - mkdocstrings:
      handlers:
        python:
          paths: [src]  # This tells mkdocstrings where the code lives
          options:
            docstring_style: sphinx
  - search

nav:
  - Introduction: index.md
  - API Reference:
      - Module BO: bo.md
      - Module SA: sa.md
      - Module Optimization: optimization.md
      - Module File_Modification: file_modification.md
      - Module Profile_Matrix_Computation: profile_matrix_computation.md
      - Module Reach_Flow: reach_flow.md
