[project]
name = "core"
version = "0.1.4"
description = "CommonRoad Python template repository."
authors = [{name = "Cyber-Physical Systems Group, Technical University of Munich", email = "<commonroad@lists.lrz.de>"}]
readme = "README.md"
requires-python = ">=3.10, <3.11"
license = "BSD-3-Clause"
dynamic = ["dependencies"]

[tool.poetry.dependencies]
python = ">=3.10, <3.11"
commonroad-io = { git = "git@gitlab.lrz.de:cps/commonroad/commonroad-io.git", branch = "develop" }
#TODO edit when available, currently pipelines do not work with it
#cr_reach_flow = {  git = "git@gitlab.lrz.de:cps/commonroad/commonroad-reach-flow.git", branch = "flofi/unfix-python-versions" }
#commonroad-route-planner = { git = "git@gitlab.lrz.de:cps/commonroad-route-planner.git", branch = "develop" }

cvxpy = "^1.6.5"

[tool.poetry.group.tests]
optional = true

[tool.poetry.group.tests.dependencies]
coverage = {version = "^7.1.0", extras = ["toml"] }

[tool.poetry.group.docs]
optional = true

[tool.poetry.group.docs.dependencies]
mkdocstrings-python = "^1.8.0"
mkdocs-material = "^9.5.12"

[tool.poetry.group.dev]
optional = true

[tool.poetry.group.dev.dependencies]
pip-licenses = "^4.3.4"
ruff = "^0.6.0"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"

# Testing
[tool.coverage.run]
source = ["core"]

# Formatting
[tool.ruff]
line-length = 120
indent-width = 4
format.quote-style = "double"
target-version = "py310"

[tool.ruff.lint]
select = ["E4", "E7", "E9", "I"]

[tool.ruff.lint.per-file-ignores]
"__init__.py" = ["E402", "F401"]
